// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enbywesecfbtxxpmvhck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVuYnl3ZXNlY2ZidHh4cG12aGNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MjAzMjgsImV4cCI6MjA2NTE5NjMyOH0.Xug8VlCMR7LkIu3TYAnl8kWt9oTp5ScRmwcolFcYiqI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);